[package]
name = "astroport-test"
version = "0.1.0"
authors = ["Astroport"]
edition = "2021"
description = "Astroport Test used for integration testing"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport-core"
homepage = "https://astroport.fi"

[features]

[dependencies]
cosmwasm-std.workspace = true